version: "3.5"
services:
  resume-api:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - frontend
      - backend
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
    networks:
      - backend
networks:
  backend:
    name: resume_backend
  frontend:
    name: resume_frontend
