version: "3.5"
services:
  api:
    build: .
    ports:
      - "443:443"
    depends_on:
      - db
    networks:
      - frontend
      - backend
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: resume_creator
      POSTGRES_USER: resume_creator
    ports:
      - "5432:5432"
    networks:
      - backend
networks:
  backend:
    name: resume_backend
  frontend:
    name: resume_frontend
